[package]
name = "bot"
version = "0.1.0"
authors = ["ebljohn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "0.3.0", features = ["full"]}
reqwest = {version = "0.10.8", features = ["json"]}
time = "0.2"
futures = "0.3.6"
