[package]
name = "bot"
version = "0.1.0"
authors = ["ebljohn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.15.0", features = ["full"]}
console = "0.15.0"
futures = "0.3"
dialoguer = "0.9.0"
